// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA7PR2yS8al3MXyA54jP0yPyHpFhX4V2sQ",
    appId: "1:1015192639352:web:9269ed5b1b95005621da8d",
    messagingSenderId: "1015192639352",
    projectId: "chatappflutter-55162",
    authDomain: "chatappflutter-55162.firebaseapp.com",
    storageBucket: "chatappflutter-55162.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7PR2yS8al3MXyA54jP0yPyHpFhX4V2sQ',
    appId: '1:1015192639352:web:9269ed5b1b95005621da8d',
    messagingSenderId: '1015192639352',
    projectId: 'chatappflutter-55162',
    authDomain: "chatappflutter-55162.firebaseapp.com",
    storageBucket: 'chatappflutter-55162.appspot.com',
  );
}
